# Generated by Django 4.1.1 on 2022-09-19 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 19, 13, 19, 17, 418261)),
        ),
    ]
