# Generated by Django 4.1.1 on 2022-09-20 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_posts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 4, 39, 32, 991928, tzinfo=datetime.timezone.utc)),
        ),
    ]
