# Generated by Django 4.1.1 on 2022-09-20 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_posts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 5, 14, 10, 402942, tzinfo=datetime.timezone.utc)),
        ),
    ]
